export class Dev {
    constructor(public no?: string,
                public devNo?: string,
                public ip?: string,
                public orgNo?: string,
                public orgName?: string,
                public awayFlag?: string,
                public devCatalog?: string,
                public devVendor?: string,
                public vendorName?: string,
                public devType?: string,
                public typeName?: string,
                public workType?: string,
                public status?: string,
                public devService?: string,
                public terminalNo?: string,
                public serial?: string,
                public address?: string,
                public buyDate?: string,
                public installDate?: string,
                public startDate?: string,
                public stopDate?: string,
                public openTime?: string,
                public closeTime?: string,
                public expireDate?: string,
                public patrolPeriod?: string,
                public cashboxLimit?: string,
                public os?: string,
                public atmcSoft?: string,
                public antiVirusSoft?: string,
                public sp?: string,
                public virtualTellerNo?: string,
                public careLevel?: string,
                public lastPmDate?: string,
                public expriePmDate?: string,
                public locateNo?: string,
                public note1?: string,
                public note2?: string,
                public note3?: string,
                public note4?: string,
                public note5?: string,
                public carrier?: string,
                public moneyOrg?: string,
                public devStatus?: string,
                public environment?: string,
                public addressCode?: string,
                public cashType?: string,
                public setupType?: string,
                public netType?: string,
                public opreateStatus?: string,
                public registrationStatus?: string,
                public commPacket?: string,
                public zipType?: string,
                public dekEncoded?: string,
                public atmpArea?: string,
                public devLogPath?: string,
                public transRate?: string,
                public serialNoInfoStatus?: number,
                public txtInfoStatus?: number,
                public checked = false,
    ) {

    }
}
