--建缓冲池
CREATE BUFFERPOOL BFPOOL32 IMMEDIATE  SIZE 250 PAGESIZE 32 K ;

--建表空间,路径要修改
CREATE TABLESPACE ZHYGSPACE PAGESIZE 32 K  MANAGED BY DATABASE  
USING (FILE '/home/db/db2data/db2inst1/ZHYGSPACE.DMS' 30000) 
EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14 
BUFFERPOOL  BFPOOL32  DROPPED TABLE RECOVERY OFF;

CREATE TABLESPACE ZHYGIDX PAGESIZE 32 K  MANAGED BY DATABASE  
USING (FILE '/home/db/db2data/db2inst1/ZHYGIDX.DMS' 30000) 
EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14 
BUFFERPOOL  BFPOOL32  DROPPED TABLE RECOVERY OFF;

ALTER TABLESPACE ZHYGSPACE AUTORESIZE YES;
ALTER TABLESPACE ZHYGIDX AUTORESIZE YES;
COMMIT

CONNECT RESET;


