create index IDX_RUNST_DEV on RUN_STATUS_TABLE (DEV_NO asc);
CREATE INDEX ST_INDEX_DEVNO ON SHORTEN_TABLE (DEV_NO ASC);
CREATE INDEX ST_INDEX_LACKTYPE ON SHORTEN_TABLE (LACK_TYPE ASC);
CREATE INDEX ST_INDEX_DATE ON SHORTEN_TABLE (LACK_DATE ASC);
CREATE INDEX CLEAR_INDEX_DEVNO ON CLEAR_TABLE (DEV_NO ASC);
CREATE INDEX IDX_ADDCASHID ON DEV_CASH_CLEAR (ADDCASH_ID DESC);
CREATE INDEX IDX_RUNST_DEVNO_DATEYMD ON RUN_STATUS_DEV_TABLE (DEV_NO, DATE_YMD ASC);

create index RCT_INDEX_DATE on RETAIN_CARD_TABLE (RETAIN_DATE ASC);
create index RCT_INDEX_DEVNO on RETAIN_CARD_TABLE (DEV_NO ASC);
create index RFDT_INDEX_DEVNO on RPT_FAULT_DEV_DATE (DEV_NO ASC);
create index RFMT_INDEX_DEVNO on RPT_FAULT_DEV_MONTH (DEV_NO ASC);
create index RFYT_INDEX_DEVNO on RPT_FAULT_DEV_YEAR (DEV_NO ASC);

create index IDX_RVCTASK_DEVNO on APPS_MODEL_SYNC_TASK (SYNCUNIT ASC);
create index IDX_RVCTASK_TIME on APPS_MODEL_SYNC_TASK (TASKSTARTTIME ASC);
create index IDX_APPSMODELVERSION_TIME on APPS_MODEL_VERSION_TABLE (UPDATE_TIME ASC);
